[main]
font=JetBrainsMono Nerd Font:size=12
terminal=alacritty -e
layer=overlay
width=40
horizontal-pad=20
vertical-pad=14
inner-pad=8

[border]
width=2
radius=10

# retro-82
[colors]
background=05182eee
text=f6dcacff
match=faa968ff
selection=134e5aff
selection-text=f6dcacff
selection-match=faa968ff
border=faa968ff
